2025-08-27 08:19:15,585 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:19:19,960 (INFO) - playground.views - Calling httpbin
2025-08-27 08:19:22,890 (INFO) - playground.views - Received the response
2025-08-27 08:19:28,765 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
2025-08-27 08:19:51,833 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:19:58,668 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
2025-08-27 08:19:59,391 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:20:05,055 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
2025-08-27 08:20:05,754 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:20:08,287 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
2025-08-27 08:20:08,936 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:20:20,848 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
2025-08-27 08:20:21,680 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:20:23,282 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
2025-08-27 08:20:23,963 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:21:11,371 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
2025-08-27 08:22:40,813 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:22:43,321 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
2025-08-27 08:22:43,999 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:22:45,457 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
Calling httpbin
Received the response
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
Calling httpbin
Received the response
/Users/masarat/development/django_projects/storefront/playground/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/masarat/development/django_projects/storefront/storefront/settings.py changed, reloading.
2025-08-27 08:35:33,421 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:35:40,356 (INFO) - playground.views - Calling httpbin
2025-08-27 08:35:43,254 (INFO) - playground.views - Received the response
2025-08-27 08:51:40,113 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 08:51:42,019 (INFO) - playground.views - Calling httpbin
2025-08-27 08:51:43,836 (INFO) - playground.views - Received the response
2025-08-27 09:44:38,265 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 09:45:59,233 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/.venv/lib/python3.13/site-packages/requests/api.py changed, reloading.
2025-08-27 09:46:01,361 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 09:46:03,022 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/.venv/lib/python3.13/site-packages/charset_normalizer/__init__.py changed, reloading.
2025-08-27 09:46:04,567 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 09:46:44,178 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/.venv/lib/python3.13/site-packages/charset_normalizer/__init__.py changed, reloading.
2025-08-27 09:46:45,014 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 09:47:13,196 (WARNING) - django.request - Unauthorized: /store/collections/
2025-08-27 09:47:13,210 (WARNING) - django.request - Forbidden: /store/collections/
2025-08-27 09:47:13,222 (WARNING) - django.request - Bad Request: /store/collections/
2025-08-27 09:48:15,732 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/.venv/lib/python3.13/site-packages/requests/compat.py changed, reloading.
2025-08-27 09:48:16,417 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 09:48:55,752 (WARNING) - django.request - Unauthorized: /store/collections/
2025-08-27 09:48:55,765 (WARNING) - django.request - Forbidden: /store/collections/
2025-08-27 09:48:55,777 (WARNING) - django.request - Bad Request: /store/collections/
2025-08-27 09:51:18,962 (INFO) - django.utils.autoreload - /Users/masarat/development/django_projects/storefront/storefront/settings/common.py changed, reloading.
2025-08-27 09:51:19,849 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-27 09:51:36,274 (WARNING) - django.request - Unauthorized: /store/collections/
2025-08-27 09:51:36,309 (WARNING) - django.request - Forbidden: /store/collections/
2025-08-27 09:51:36,345 (WARNING) - django.request - Bad Request: /store/collections/
2025-08-27 10:03:33,463 (INFO) - playground.views - Calling httpbin
2025-08-27 10:03:36,976 (INFO) - playground.views - Received the response
2025-08-30 20:31:26,406 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:33:25,800 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/storefront/settings/dev.py changed, reloading.
2025-08-30 20:33:27,628 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:33:49,162 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/storefront/settings/dev.py changed, reloading.
2025-08-30 20:33:51,076 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:33:55,072 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/storefront/settings/dev.py changed, reloading.
2025-08-30 20:33:57,344 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:34:01,474 (ERROR) - django.request - Internal Server Error: /
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.ProgrammingError: (1146, "Table 'storefront2.silk_request' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/middleware.py", line 87, in __call__
    self.process_request(request)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/middleware.py", line 143, in process_request
    request_model = RequestModelFactory(request).construct_request_model()
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/model_factory.py", line 231, in construct_request_model
    request_model = models.Request.objects.create(
        path=path,
    ...<3 lines>...
        view_name=view_name,
        body=body)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/models.py", line 195, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: (1146, "Table 'storefront2.silk_request' doesn't exist")
2025-08-30 20:34:03,003 (ERROR) - django.request - Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.ProgrammingError: (1146, "Table 'storefront2.silk_request' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/middleware.py", line 87, in __call__
    self.process_request(request)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/middleware.py", line 143, in process_request
    request_model = RequestModelFactory(request).construct_request_model()
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/model_factory.py", line 231, in construct_request_model
    request_model = models.Request.objects.create(
        path=path,
    ...<3 lines>...
        view_name=view_name,
        body=body)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/models.py", line 195, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: (1146, "Table 'storefront2.silk_request' doesn't exist")
2025-08-30 20:34:19,711 (ERROR) - django.request - Internal Server Error: /store/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.ProgrammingError: (1146, "Table 'storefront2.silk_request' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/middleware.py", line 87, in __call__
    self.process_request(request)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/middleware.py", line 143, in process_request
    request_model = RequestModelFactory(request).construct_request_model()
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/model_factory.py", line 231, in construct_request_model
    request_model = models.Request.objects.create(
        path=path,
    ...<3 lines>...
        view_name=view_name,
        body=body)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/models.py", line 195, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: (1146, "Table 'storefront2.silk_request' doesn't exist")
2025-08-30 20:34:20,144 (ERROR) - django.request - Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.ProgrammingError: (1146, "Table 'storefront2.silk_request' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/middleware.py", line 87, in __call__
    self.process_request(request)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/middleware.py", line 143, in process_request
    request_model = RequestModelFactory(request).construct_request_model()
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/model_factory.py", line 231, in construct_request_model
    request_model = models.Request.objects.create(
        path=path,
    ...<3 lines>...
        view_name=view_name,
        body=body)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/silk/models.py", line 195, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: (1146, "Table 'storefront2.silk_request' doesn't exist")
2025-08-30 20:35:31,331 (WARNING) - django.request - Not Found: /favicon.ico
2025-08-30 20:35:51,361 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 20:37:08,269 (WARNING) - django.request - Bad Request: /store/products/like/
2025-08-30 20:41:34,325 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 395, in post
    liked_item = serializer.save()
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py", line 306, in create
    already_liked = user.likeditem_set.filter(object_id=product_id).exists()
                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'likeditem_set'
2025-08-30 20:42:27,376 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py changed, reloading.
2025-08-30 20:42:29,410 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:42:33,434 (WARNING) - django.request - Unauthorized: /store/products/like/
2025-08-30 20:43:17,899 (WARNING) - django.request - Unauthorized: /auth/users/
2025-08-30 20:43:25,340 (WARNING) - django.request - Unauthorized: /auth/users/
2025-08-30 20:44:18,052 (WARNING) - django.request - Method Not Allowed: /auth/jwt/create
2025-08-30 20:45:21,231 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 20:45:37,457 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/fields/__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Product'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 395, in post
    liked_item = serializer.save()
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py", line 306, in create
    already_liked = user.likeditem_set.filter(object_id=product_id).exists()
                    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<6 lines>...
        summarize=summarize,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
    raise e.__class__(
        "Field '%s' expected a number but got %r." % (self.name, value),
    ) from e
TypeError: Field 'object_id' expected a number but got <Product: Bread Ww Cluster>.
2025-08-30 20:48:45,158 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 20:48:46,863 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:48:52,378 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 20:48:56,057 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:49:02,000 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 20:49:03,082 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:49:07,081 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 20:49:08,394 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:50:35,712 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 20:50:50,200 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 395, in post
    liked_item = serializer.save()
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py", line 316, in create
    return liked_item
           ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'liked_item' where it is not associated with a value
2025-08-30 20:58:49,599 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 20:58:51,674 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:58:54,886 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 20:58:57,229 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:59:02,816 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 20:59:04,677 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:59:08,196 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 20:59:10,152 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 20:59:11,473 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 20:59:33,726 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 395, in post
    liked_item = serializer.save()
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 211, in save
    assert self.instance is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: `create()` did not return an object instance.
2025-08-30 21:01:15,148 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:01:16,673 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:01:30,366 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:01:31,480 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:01:39,509 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 21:02:52,021 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 395, in post
    liked_item = serializer.save()
TypeError: LikeProductSerializer.save() missing 1 required positional argument: 'validated_data'
2025-08-30 21:03:19,729 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:03:21,392 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:03:23,013 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 21:03:44,400 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 398, in post
    return Response(LikedItemSerializer(liked_item).data, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py", line 327, in get_product
    if liked_item.content_object and isinstance(liked_item.content_object, Product):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'content_object'
2025-08-30 21:15:52,524 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/likes/models.py changed, reloading.
2025-08-30 21:15:55,348 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:15:57,893 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/likes/models.py changed, reloading.
2025-08-30 21:15:59,103 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:16:02,721 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/likes/models.py changed, reloading.
2025-08-30 21:16:04,560 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:16:13,869 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/likes/models.py changed, reloading.
2025-08-30 21:16:15,220 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:16:22,798 (WARNING) - django.request - Unauthorized: /store/products/like/
2025-08-30 21:16:29,078 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 21:17:14,285 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 398, in post
    return Response(LikedItemSerializer(liked_item).data, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py", line 327, in get_product
    if liked_item.content_object and isinstance(liked_item.content_object, Product):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'content_object'
2025-08-30 21:20:38,824 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:20:41,178 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:20:47,165 (WARNING) - django.request - Unauthorized: /store/products/like/
2025-08-30 21:20:52,618 (WARNING) - django.request - Unauthorized: /store/products/like/
2025-08-30 21:20:54,658 (WARNING) - django.request - Unauthorized: /store/products/like/
2025-08-30 21:21:03,236 (WARNING) - django.request - Unauthorized: /store/products/like/
2025-08-30 21:21:09,034 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 21:21:33,591 (WARNING) - django.request - Bad Request: /store/products/like/
2025-08-30 21:21:58,095 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 398, in post
    return Response(LikedItemSerializer(liked_item).data, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py", line 325, in get_product
    return ProductSerializer(liked_item.content_object).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/relations.py", line 373, in to_representation
    assert 'request' in self.context, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: `HyperlinkedRelatedField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer.
2025-08-30 21:22:26,306 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:22:27,382 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:23:18,969 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:23:20,775 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:23:23,687 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:23:24,901 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:23:29,943 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:23:31,557 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:23:37,704 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:23:40,148 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:23:42,616 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 21:24:04,818 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 398, in post
    return Response(LikedItemSerializer(liked_item).data, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py", line 329, in get_product
    return ProductSerializer(liked_item.content_object).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/relations.py", line 373, in to_representation
    assert 'request' in self.context, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: `HyperlinkedRelatedField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer.
2025-08-30 21:24:27,899 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py changed, reloading.
2025-08-30 21:24:31,187 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:24:34,902 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py changed, reloading.
2025-08-30 21:24:35,978 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:24:42,021 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py changed, reloading.
2025-08-30 21:24:43,257 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:24:46,319 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 21:24:53,678 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 398, in post
    return Response(LikedItemSerializer(liked_item, context={'request': request}).data, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py", line 329, in get_product
    return ProductSerializer(liked_item.content_object).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/relations.py", line 373, in to_representation
    assert 'request' in self.context, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: `HyperlinkedRelatedField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer.
2025-08-30 21:25:03,538 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py changed, reloading.
2025-08-30 21:25:05,288 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:25:07,633 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 21:25:14,849 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 398, in post
    return Response(LikedItemSerializer(liked_item, context={'request': request}).data, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py", line 329, in get_product
    return ProductSerializer(liked_item.content_object).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/relations.py", line 373, in to_representation
    assert 'request' in self.context, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: `HyperlinkedRelatedField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer.
2025-08-30 21:25:46,363 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py changed, reloading.
2025-08-30 21:25:47,645 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:25:51,904 (WARNING) - django.request - Method Not Allowed: /store/products/like/
2025-08-30 21:25:59,408 (ERROR) - django.request - Internal Server Error: /store/products/like/
Traceback (most recent call last):
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/views.py", line 398, in post
    return Response(LikedItemSerializer(liked_item, context={'request': request}).data, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py", line 329, in get_product
    return ProductSerializer(liked_item.content_object).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 540, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/.venv/lib/python3.13/site-packages/rest_framework/relations.py", line 373, in to_representation
    assert 'request' in self.context, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: `HyperlinkedRelatedField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer.
2025-08-30 21:31:02,912 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:31:05,020 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:31:13,162 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:31:14,346 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:31:29,303 (INFO) - django.utils.autoreload - /Users/ahmedezzat/Documents/The Ultimate Django Series 1-3/The Ultimate Django Series Part 2/Resources/Code/1- Getting Started/Start/storefront2/store/serializers.py changed, reloading.
2025-08-30 21:31:30,320 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2025-08-30 21:31:41,662 (WARNING) - django.request - Method Not Allowed: /store/products/like/
